name: Android Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: uduntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android Emulator + Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: pixel_4
          avd-name: Medium_Phone
          emulator-options: -no-window -no-audio -no-boot-anim
          script: |
            adb install app/udp.reeng.app.apk

            npm install -g appium
            appium driver install uiautomator2
            appium &
            sleep 5

            dotnet test --logger "console;verbosity=detailed"
        env:
          OWNEREQUIPMENT__PHONENUMBER: ${{ secrets.OWNER_PHONE }}
          OWNEREQUIPMENT__PASSWORD: ${{ secrets.OWNER_PASSWORD }}
          SERVICECOMPANIES__PHONENUMBER: ${{ secrets.SERVICE_PHONE }}
          SERVICECOMPANIES__PASSWORD: ${{ secrets.SERVICE_PASSWORD }}